#from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response #used to return responses from APIViews
from rest_framework import status #it is a list of handy HTTP status codes that you can use when returning responses from your api
from . import serializers
from rest_framework import viewsets
# Create your views here.

class HelloApiView(APIView): #allows us to define the app logic for our endpoint we assign to this view
    """Test API View"""
    serializer_class = serializers.HelloSerializer #this is used to tell our apiview what data to expect when making post, put and patch requests

    def get(self, request, format=None): #allows us to accept and respond to GET request to our API
        """Returns a list of APIView features"""
        #the request argument is passed in by DRF and contains details of the request made to the API
        #the format argument is used to add format suffix to the end of the endpoint url (we will not use it here)
        an_apiview = [
            'Uses HTTP methods as functions (get, post, patch, put, delete)',
            'Is similar to a traditional Django View',
            'Gives you the most control over your application logic',
            'Is mapped manually to URLs',
        ] # a list that describes all of the features of an APIView (just for demonstration)

        return Response({'message': 'Hello!', 'an_apiview': an_apiview})

    def post(self, request):
        """Create a hello message with our name"""
        serializer = self.serializer_class(data=request.data) # retrieve the serializer and pass in the data sent in the request

        if serializer.is_valid():
            name = serializer.validated_data.get('name') # retrieve the name field
            message = f'Hello {name}' # a message to demonstrate the POST method
            return Response({'message': message})
        else:
            return Response(
            serializer.errors,# return the errors generated by the serializer based on the validation rules there
            status=status.HTTP_400_BAD_REQUEST
            )

    def put(self, request, pk=None): # the pk is to take the id of the object to be updated with the put request (we are not supporing it here because we will just returning a standard response for demonstration)
        """handle updating an entire object"""
        return Response({'method': 'PUT'})

    def patch(self, request, pk=None): # a partial update for example is updating only the last name field not the whole name (object), unlike the put method
        """Handle a partial update of an object"""
        return Response({'method': 'PATCH'})

    def delete(self, request, pk=None):
        """Deletes an object"""
        return Response({'method': 'DELETE'})


class HelloViewSet(viewsets.ViewSet):
    """Test API ViewSet"""
    serializer_class = serializers.HelloSerializer

    def list(self, request): # For getting a list of objects - typically an HTTP GET to the root of the URL endpoint linked to our viewset
        """Return a hello message""" # it lists a set of objects that our viewset represents

        a_viewset = [ #typical features of the viewset
            'Uses actions (list, create, retrieve, update, partial_update, destroy)',
            'Automatically maps to URLs using Routers',
            'Provides more functionality with less code',
        ]

        return Response({'message': 'Hello!', 'a_viewset': a_viewset})

    def create(self, request):
        """Create a new hello message"""
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            name = serializer.validated_data.get('name')
            message = f'Hello {name}!'
            return Response({'message': message})
        else:
            return Response(
                serializer.errors,
                status.HTTP_400_BAD_REQUEST,
            )

    def retrieve(self, request, pk=None):
        """Handle getting an object by its ID"""
        return Response({'http_method': 'GET'})

    def update(self, request, pk=None):
        """Handle updating an object"""
        return Response({'http_method': 'PUT'})

    def partial_update(self, request, pk=None):
        """Handle updating part of an object"""
        return Response({'http_method': 'PATCH'})

    def destroy(self, request, pk=None):
        """Handle removing an object"""
        return Response({'http_method': 'DELETE'})
